version: '3.8'
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=ktordb
      - MYSQL_USER=ktoruser
      - MYSQL_PASSWORD=ktorpassword
    ports:
      - "3306:3306"

  backend:
    image: ktor-profiling:latest
    depends_on:
      - db
    environment:
      - ENVIRONMENT=dev
    restart: always
    ports:
      - "8082:8082"

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring:/etc/prometheus/
    links:
      - backend

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    user: "104"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    links:
      - backend
      - prometheus